list_encounter_types = (
    "Psicoterapia individual",
    "Intervención en crisis",
    "Asesoría",
    "Informe",
    "Certificado",
    "Entrevista",
    "Psicoterapia familiar",
    "Psicoterapia de pareja",
    "Ficha guarderia",
    "Valoración psicológica",
    "Valoración pre ocupacional",
    "Valoración licencia",
    "Contención",
    "Visita domiciliaria",
    "Cierre de proceso",
    "Terapia de juego",
    "Asesoría académica",
    "Atención de necesidades educativas especiales",
    "Orientación vocacional y profesional",
)

tipos_de_paciente =  (
                        "Estudiante",
                        "Egresado",
                        "Trabajador",
                        "Docente",
                        "Jubilado",
                        "Familiar",
                    )